# Minimal configuration to impersonate NGINX Ingress
ingressClass:
  enabled: true
  isDefaultClass: true
  name: "nginx" # Overrides default 'traefik' to hijack NGINX ingress requests

providers:
  kubernetesIngress:
    enabled: true
    # Allows Traefik to look at all namespaces for standard Ingress objects
    publishedService:
      enabled: true

# Configures the service for local development
service:
  enabled: true
  type: LoadBalancer # Works out-of-the-box with Minikube, Kind, or Docker Desktop
