ingressClass:
  enabled: true
  isDefaultClass: false
  name: "traefik"

providers:
  kubernetesIngress:
    enabled: false
    publishedService:
      enabled: true
  kubernetesIngressNginx:
    enabled: true
    ingressClass: "nginx"  
    ingressClassByName: true       

service:
  enabled: true
  type: LoadBalancer
